spring:
  application:
    name: airline-flight-service
  cloud:
    config:
      uri: http://localhost:8888  # Configuration Center Address
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/